export const countryData = {
  "afghanistan": ["china", "iran", "pakistan", "tajikistan", "turkmenistan", "uzbekistan"],
  "albania": ["greece", "kosovo", "montenegro"],
  "algeria": ["libya", "mali", "mauritania", "morocco", "niger", "tunisia", "western-sahara"],
  "angola": [ "democratic-republic-of-the-congo", "namibia", "zambia"],
  "antigua-and-barbuda": [],
  "argentina": ["bolivia", "brazil", "chile", "paraguay", "uruguay"],
  "armenia": ["azerbaijan", "georgia", "iran", "turkey"],
  "australia": [],
  "austria": ["czech-republic", "germany", "hungary", "italy", "slovakia", "slovenia", "switzerland"],
  "azerbaijan": ["armenia", "georgia", "iran", "russia", "turkey"],
  "bahamas": [],
  "bahrain": [],
  "bangladesh": ["india", "myanmar"],
  "barbados": [],
  "belarus": ["latvia", "lithuania", "poland", "russia", "ukraine"],
  "belgium": ["france", "germany", "luxembourg", "netherlands"],
  "belize": ["guatemala", "mexico"],
  "benin": ["burkina-faso", "niger", "nigeria", "togo"],
  "bhutan": ["china", "india"],
  "bolivia": ["argentina", "brazil", "chile", "paraguay", "peru"],
  "bosnia-and-herzegovina": ["croatia", "montenegro", "serbia"],
  "botswana": ["namibia", "south-africa", "zambia", "zimbabwe"],
  "brazil": ["argentina", "bolivia", "colombia", "french-guiana", "guyana", "paraguay", "peru", "suriname", "uruguay", "venezuela"],
  "bulgaria": ["greece", "romania", "serbia", "turkey"],
  "burkina-faso": ["benin",  "ghana", "mali", "niger", "togo"],
  "burundi": ["democratic-republic-of-the-congo", "rwanda", "tanzania"],
  "cambodia": [ "thailand", "vietnam"],
  "cameroon": ["central-african-republic", "chad",  "equatorial-guinea", "gabon", "nigeria"],
  "canada": ["united-states"],
  "cape-verde": [],
  "central-african-republic": ["cameroon", "chad",  "democratic-republic-of-the-congo", "south-sudan", "sudan"],
  "chad": ["cameroon", "central-african-republic", "libya", "niger", "nigeria", "sudan"],
  "chile": ["argentina", "bolivia", "peru"],
  "china": ["afghanistan", "bhutan", "india", "kazakhstan", "kyrgyzstan", "mongolia", "myanmar", "nepal", "pakistan", "russia", "tajikistan", "vietnam"],
  "colombia": ["brazil", "ecuador", "panama", "peru", "venezuela"],
  "comoros": [],
  "costa-rica": ["nicaragua", "panama"],
  "croatia": ["bosnia-and-herzegovina", "hungary", "montenegro", "serbia", "slovenia"],
  "cuba": [],
  "cyprus": [],
  "czech-republic": ["austria", "germany", "poland", "slovakia"],
  "democratic-republic-of-the-congo": ["angola", "burundi", "central-african-republic", "rwanda", "south-sudan", "tanzania", "uganda", "zambia"],
  "denmark": ["germany"],
  "djibouti": ["eritrea", "ethiopia", "somalia"],
  "dominica": [],
  "dominican-republic": ["haiti"],
  "ecuador": ["colombia", "peru"],
  "egypt": ["israel", "libya", "palestine", "sudan"],
  "el-salvador": ["guatemala", "honduras"],
  "equatorial-guinea": ["cameroon", "gabon"],
  "eritrea": ["djibouti", "ethiopia", "sudan"],
  "estonia": ["latvia", "russia"],
  "ethiopia": ["djibouti", "eritrea", "kenya", "somalia", "south-sudan", "sudan"],
  "fiji": [],
  "finland": ["norway", "russia", "sweden"],
  "france": [ "belgium", "germany", "italy", "luxembourg", "spain", "switzerland"],
  "gabon": ["cameroon", "equatorial-guinea"],
  "georgia": ["armenia", "azerbaijan", "russia", "turkey"],
  "germany": ["austria", "belgium", "czech-republic", "denmark", "france", "luxembourg", "netherlands", "poland", "switzerland"],
  "ghana": ["burkina-faso",  "togo"],
  "greece": ["albania", "bulgaria", "turkey"],
  "grenada": [],
  "guatemala": ["belize", "el-salvador", "honduras", "mexico"],
  "guinea": [ "guinea-bissau", "liberia", "mali", "senegal", "sierra-leone"],
  "guinea-bissau": ["guinea", "senegal"],
  "guyana": ["brazil", "suriname", "venezuela"],
  "haiti": ["dominican-republic"],
  "honduras": ["el-salvador", "guatemala", "nicaragua"],
  "hungary": ["austria", "croatia", "romania", "serbia", "slovakia", "slovenia", "ukraine"],
  "iceland": [],
  "india": ["afghanistan", "bangladesh", "bhutan", "china", "myanmar", "nepal", "pakistan"],
  "indonesia": ["malaysia", "papua-new-guinea"],
  "iran": ["afghanistan", "armenia", "azerbaijan", "iraq", "pakistan", "turkey", "turkmenistan"],
  "iraq": ["iran", "jordan", "kuwait", "saudi-arabia", "syria", "turkey"],
  "ireland": ["united-kingdom"],
  "israel": ["egypt", "jordan", "lebanon", "palestine", "syria"],
  "italy": ["austria", "france", "slovenia", "switzerland",],
  "jamaica": [],
  "japan": [],
  "jordan": ["iraq", "israel", "palestine", "saudi-arabia", "syria"],
  "kazakhstan": ["china", "kyrgyzstan", "russia", "turkmenistan", "uzbekistan"],
  "kenya": ["ethiopia", "somalia", "south-sudan", "tanzania", "uganda"],
  "kiribati": [],
  "kosovo": ["albania", "montenegro", "serbia"],
  "kuwait": ["iraq", "saudi-arabia"],
  "kyrgyzstan": ["china", "kazakhstan", "tajikistan", "uzbekistan"],
  "latvia": ["belarus", "estonia", "lithuania", "russia"],
  "lebanon": ["israel", "syria"],
  "lesotho": ["south-africa"],
  "liberia": [ "guinea", "sierra-leone"],
  "libya": ["algeria", "chad", "egypt", "niger", "sudan", "tunisia"],
  "lithuania": ["belarus", "latvia", "poland", "russia"],
  "luxembourg": ["belgium", "france", "germany"],
  "madagascar": [],
  "malawi": ["mozambique", "tanzania", "zambia"],
  "malaysia": [ "indonesia", "thailand"],
  "maldives": [],
  "mali": ["algeria", "burkina-faso", "guinea", "mauritania", "niger", "senegal"],
  "malta": [],
  "marshall-islands": [],
  "mauritania": ["algeria", "mali", "senegal", "western-sahara"],
  "mauritius": [],
  "mexico": ["belize", "guatemala", "united-states"],
  "micronesia": [],
  "moldova": ["romania", "ukraine"],
  "mongolia": ["china", "russia"],
  "montenegro": ["albania", "bosnia-and-herzegovina", "croatia", "kosovo", "serbia"],
  "morocco": ["algeria", "spain", "western-sahara"],
  "mozambique": [ "malawi", "south-africa", "tanzania", "zambia", "zimbabwe"],
  "myanmar": ["bangladesh", "china", "india", "thailand"],
  "namibia": ["angola", "botswana", "south-africa", "zambia"],
  "nauru": [],
  "nepal": ["china", "india"],
  "netherlands": ["belgium", "germany"],
  "new-zealand": [],
  "nicaragua": ["costa-rica", "honduras"],
  "niger": ["algeria", "benin", "burkina-faso", "chad", "libya", "mali", "nigeria"],
  "nigeria": ["benin", "cameroon", "chad", "niger"],
  "norway": ["finland", "russia", "sweden"],
  "oman": ["saudi-arabia", "united-arab-emirates", "yemen"],
  "pakistan": ["afghanistan", "china", "india", "iran"],
  "palau": [],
  "palestine": ["egypt", "israel", "jordan"],
  "panama": ["colombia", "costa-rica"],
  "papua-new-guinea": ["indonesia"],
  "paraguay": ["argentina", "bolivia", "brazil"],
  "peru": ["bolivia", "brazil", "chile", "colombia", "ecuador"],
  "philippines": [],
  "poland": ["belarus", "czech-republic", "germany", "lithuania", "russia", "slovakia", "ukraine"],
  "portugal": ["spain"],
  "qatar": ["saudi-arabia"],
  "romania": ["bulgaria", "hungary", "moldova", "serbia", "ukraine"],
  "russia": ["azerbaijan", "belarus", "china", "estonia", "finland", "georgia", "kazakhstan", "latvia", "lithuania", "mongolia", "norway", "poland", "ukraine"],
  "rwanda": ["burundi", "democratic-republic-of-the-congo", "tanzania", "uganda"],
  "saint-kitts-and-nevis": [],
  "saint-lucia": [],
  "saint-vincent-and-the-grenadines": [],
  "samoa": [],
  "sao-tome-and-principe": [],
  "saudi-arabia": ["iraq", "jordan", "kuwait", "oman", "qatar", "united-arab-emirates", "yemen"],
  "serbia": ["bosnia-and-herzegovina", "bulgaria", "croatia", "hungary", "kosovo", "montenegro", "romania"],
  "seychelles": [],
  "sierra-leone": ["guinea", "liberia"],
  "singapore": [],
  "slovakia": ["austria", "czech-republic", "hungary", "poland", "ukraine"],
  "slovenia": ["austria", "croatia", "italy", "hungary"],
  "solomon-islands": [],
  "somalia": ["djibouti", "ethiopia", "kenya"],
  "south-africa": ["botswana",  "lesotho", "mozambique", "namibia", "zimbabwe"],
  "south-sudan": ["central-african-republic", "democratic-republic-of-the-congo", "ethiopia", "kenya", "sudan", "uganda"],
  "spain": [ "france", "morocco", "portugal"],
  "sri-lanka": [],
  "sudan": ["central-african-republic", "chad", "egypt", "eritrea", "ethiopia", "libya", "south-sudan"],
  "suriname": ["brazil", "french-guiana", "guyana"],
  "sweden": ["finland", "norway"],
  "switzerland": ["austria", "france", "germany", "italy"],
  "syria": ["iraq", "israel", "jordan", "lebanon", "turkey"],
  "taiwan": [],
  "tajikistan": ["afghanistan", "china", "kyrgyzstan", "uzbekistan"],
  "tanzania": ["burundi", "democratic-republic-of-the-congo", "kenya", "malawi", "mozambique", "rwanda", "uganda", "zambia"],
  "thailand": ["cambodia","malaysia", "myanmar"],
  "togo": ["benin", "burkina-faso", "ghana"],
  "tonga": [],
  "trinidad-and-tobago": [],
  "tunisia": ["algeria", "libya"],
  "turkey": ["armenia", "azerbaijan", "bulgaria", "georgia", "greece", "iran", "iraq", "syria"],
  "turkmenistan": ["afghanistan", "iran", "kazakhstan", "uzbekistan"],
  "tuvalu": [],
  "uganda": ["democratic-republic-of-the-congo", "kenya", "rwanda", "south-sudan", "tanzania"],
  "ukraine": ["belarus", "hungary", "moldova", "poland", "romania", "russia", "slovakia"],
  "united-arab-emirates": ["oman", "saudi-arabia"],
  "united-kingdom": ["ireland"],
  "united-states": ["canada", "mexico"],
  "uruguay": ["argentina", "brazil"],
  "uzbekistan": ["afghanistan", "kazakhstan", "kyrgyzstan", "tajikistan", "turkmenistan"],
  "vanuatu": [],
  "venezuela": ["brazil", "colombia", "guyana"],
  "vietnam": ["cambodia", "china"],
  "western-sahara": ["algeria", "mauritania", "morocco"],
  "yemen": ["oman", "saudi-arabia"],
  "zambia": ["angola", "botswana", "democratic-republic-of-the-congo", "malawi", "mozambique", "namibia", "tanzania", "zimbabwe"],
  "zimbabwe": ["botswana", "mozambique", "south-africa", "zambia"]
}